# The configuration file for Web.Auto CI/CD tool.
# https://docs.web.auto/user-manuals/evaluator/configuration/reference/introduction

version: 2

artifacts:
  - name: main
    metadata:
      play-ondemand.ci.web.auto/buildspec: Autoware-Humble_v0.29.0
    build:
      type: custom
      runtime:
        type: standard1/amd64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
            - simulator.repos
          import_path: src
      environment_variables:
        AUTOWARE_PATH: /opt/autoware
        DEBIAN_FRONTEND: noninteractive
        LANG: C.UTF-8
      linux_parameters:
        kernel_version: 5.19.0-50-generic
      phases:
        - name: environment-setup
          user: root
          exec: ./.webauto-ci/main/environment-setup/run.sh
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/main/environment-setup/**/*
        - name: autoware-setup
          user: autoware
          exec: ./.webauto-ci/main/autoware-setup/run.sh
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/main/autoware-setup/**/*
              - ansible/**/*
              - ansible-galaxy-requirements.yaml
              - amd64.env
          incremental_build:
            enabled: true
        - name: autoware-build
          user: autoware
          exec: ./.webauto-ci/main/autoware-build/run.sh
          environment_variables:
            PARALLEL_WORKERS: "32"
            CCACHE_DIR: /tmp/build/cache/ccache
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
            - name: ccache
              mountpoint: /tmp/build/cache/ccache
          build_result_reuse:
            key_files:
              - .webauto-ci/main/autoware-build/**/*
              - src/**/*
      base_container_image:
        from: ubuntu:22.04
      output_container_image:
        from: autoware-build
        workdir: /opt/autoware
        user: autoware

simulations:
  - name: perception
    type: perception
    simulator:
      deployment:
        type: container
        artifact: main
    runtime:
        type: gpu1/amd64/large
    pre_tasks:
        exec: source /home/autoware/autoware.proj/install/setup.bash && ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint_tiny model_path:=/home/autoware/autoware_data/lidar_centerpoint model_param_path:=$(ros2 pkg prefix lidar_centerpoint --share)/config/centerpoint_tiny.param.yaml build_only:=true
        mounts:
          volume: model
    volumes:
      name: model
      path: /home/autoware/autoware_data/lidar_centerpoint
      preserve_original_files: true
  - name: localization
    type: localization
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/large
  - name: lexus_planning_sim
    type: planning_sim_v2
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium
      parameters:
        launch_autoware: "true"
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe/20250130
        vehicle_model: sample_vehicle
        sensor_model: sample_sensor_kit
        initialize_duration: "90"
        launch_visualization: "false"

release:
  components:
    - name: planning
      deployment:
        type: container
        artifact: main
    - name: perception
      deployment:
        type: container
        artifact: main
